Fix NoClassDefFoundError for autoconfig
Switched from the old autoconfig to Shedaniel's fork within cloth-config which fixed the modmenu error
Also fixed some warnings

Signed-off-by: TreyRuffy <TreyRuffy@users.noreply.github.com>